[features]
seeds = false
skip-lint = false
[programs.localnet]
big_list = "2dcZKYRfijTg3TMU2xocaCKVv6LJTzzdwtLBbMUyKzKi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ryankane/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://rpc.helius.xyz/?api-key=ca8112d0-9431-4b84-beac-6df95719434f"
[[test.validator.clone]]
address = "3XXuUFfweXBwFgFfYaejLvZE4cGZiHgKiGfMtdxNzYmv"